### ISSUE TITLE
Support for parameters on send_template

### ISSUE THREAD

**Issue by dardoguidobono** [JS-Hub-ZW/heyooh#2]
https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-message-templates

add support for setting the header parameters
`
{ "messaging_product": "whatsapp", "to": "5XXXXXXXXXXX", "type": "template", "template": { "name": "test_template", "language": { "code": "es_MX" }, "components": [{ "type": "header", "parameters": [ { "type": "text","text": "111" } ] } ] } }
`
and body parameters like this
`{ "messaging_product": "whatsapp", "to": "5XXXXXXXXXXX", "type": "template", "template": { "name": "prueba_confirmacion_turno", "language": { "code": "es_MX" }, "components": [{ "type": "body", "parameters": [ { "type": "text","text": "111" },{ "type": "text","text": "222" },{ "type": "text","text": "333" },{ "type": "text","text": "444" } ] } ] } }
`

**Comment by phoscoder** [comment]
Hi @dardoguidobono, in the meantime i am going to add an components args to send_template

```javascript
let components = [
         {
            "type":"body",
            "parameters":[
               {
                  "type":"text",
                  "text":"111"
               },
               {
                  "type":"text",
                  "text":"222"
               },
               {
                  "type":"text",
                  "text":"333"
               },
               {
                  "type":"text",
                  "text":"444"
               }
            ]
         }
      ]

...


await messenger.send_template("name_here", "recipient_id", components)
```

**Comment by vermapranay2rp** [comment]
still no support for header parameters
